from typing import Protocol, Sequence

from .models import Manga, MangaCover, MangaAltTitulo

class IMangaRepository(Protocol):
    async def get_mangas(
        self,
        page: int = 1,
        page_size: int = 24,
        can_see_nsfw: bool = False,
        titulo: str | None = None,
        estado_desc: str | None = None,
        demografia_desc: str | None = None,
        tipo_serie: str | None = None,
        autor_id: int | None = None,
        fecha_from: str | None = None,
        fecha_to: str | None = None,
        vigente: bool | None = None,
        erotico: bool | None = None,
        ordering: str = "-creado_en",
        search: str | None = None,
    ) -> tuple[Sequence[Manga], int]: ...

    async def get_manga_by_id(self, manga_id: int, can_see_nsfw: bool = False) -> Manga | None: ...

    async def get_manga_by_slug(self, slug: str, can_see_nsfw: bool = False) -> Manga | None: ...

    async def create_manga(self, data: dict) -> Manga: ...

    async def update_manga(self, manga_id: int, data: dict) -> Manga | None: ...

    async def increment_view_count(self, manga_id: int) -> int | None: ...

    async def get_total_count(self, can_see_nsfw: bool = False) -> int: ...

    async def get_max_id(self, can_see_nsfw: bool = False) -> int | None: ...

    async def get_all_ids(self, can_see_nsfw: bool = False) -> Sequence[int]: ...

    async def get_mangas_by_ids(self, ids: list[int], can_see_nsfw: bool = False) -> Sequence[Manga]: ...

    async def get_manga_id_gte(self, pk: int, can_see_nsfw: bool = False) -> int | None: ...

    async def get_manga_gte_id(self, pk: int, can_see_nsfw: bool = False) -> Manga | None: ...

    async def get_mangas_excluding_ids(self, exclude_ids: set[int], limit: int, can_see_nsfw: bool = False) -> Sequence[Manga]: ...

    async def get_home_data(self) -> dict[str, Sequence[Manga]]: ...

    async def get_manga_covers(self, manga_id: int) -> Sequence[MangaCover]: ...

    async def get_manga_alt_titulos(self, manga_id: int) -> Sequence[MangaAltTitulo]: ...
