# Generated by Django 5.2.6 on 2025-12-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0002_alter_manga_cover_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga_tag',
            name='manga',
            field=models.ForeignKey(db_column='MTG_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='ApiCore.manga'),
        ),
    ]
