# Generated by Django 5.2.6 on 2025-12-11 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(db_column='AUT_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='AUT_NOMBRE', max_length=100)),
                ('tipo_autor', models.CharField(choices=[('mangaka', 'mangaka'), ('ilustrador', 'ilustrador'), ('guionista', 'guionista')], db_column='AUT_TIPO_AUTOR', default='mangaka', max_length=20)),
                ('foto', models.CharField(db_column='AUT_FOTO', max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='AUT_CREACION')),
                ('vigente', models.BooleanField(db_column='AUT_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'apicore_autores',
            },
        ),
        migrations.CreateModel(
            name='demografia',
            fields=[
                ('id', models.BigAutoField(db_column='DEM_ID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DEM_DESCRIPCION', max_length=255, null=True)),
                ('color', models.CharField(db_column='DEM_COLOR', max_length=7, null=True)),
                ('vigente', models.BooleanField(db_column='DEM_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'apicore_demografia',
            },
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id', models.BigAutoField(db_column='EST_ID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='EST_DESCRIPCION', max_length=255, null=True)),
                ('vigente', models.BooleanField(db_column='EST_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'apicore_estados',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(db_column='TAG_ID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='TAG_DESCRIPCION', max_length=255, null=True)),
                ('vigente', models.BooleanField(db_column='TAG_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'apicore_tags',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=10)),
                ('view_name', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id', models.BigAutoField(db_column='MNG_ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='MNG_CODIGO', max_length=50, null=True, unique=True)),
                ('titulo', models.CharField(db_column='MNG_TITULO', max_length=200)),
                ('sinopsis', models.TextField(db_column='MNG_SINOPSIS', null=True)),
                ('tipo_serie', models.CharField(choices=[('manga', 'manga'), ('manhwa', 'manhwa'), ('manhua', 'manhua'), ('one shot', 'one shot'), ('novel', 'novel'), ('doujinshi', 'doujinshi'), ('comic', 'comic')], db_column='MNG_TIPO_SERIE', db_index=True, default='manga', max_length=20)),
                ('fecha_lanzamiento', models.DateField(db_column='MNG_FECHA_LANZAMIENTO', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='MNG_CREACION')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='MNG_ACTUALIZACION')),
                ('vigente', models.BooleanField(db_column='MNG_VIGENTE', default=True)),
                ('vistas', models.PositiveIntegerField(db_column='MNG_VISTA', default=0)),
                ('erotico', models.BooleanField(db_column='MNG_EROTICO', default=False)),
                ('autor', models.ForeignKey(db_column='MNG_AUTOR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.autores')),
                ('demografia', models.ForeignKey(db_column='MNG_DEMOGRAFIA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.demografia')),
                ('estado', models.ForeignKey(db_column='MNG_ESTADO_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.estados')),
            ],
            options={
                'db_table': 'apicore_manga',
            },
        ),
        migrations.CreateModel(
            name='manga_alt_titulo',
            fields=[
                ('id', models.BigAutoField(db_column='MAT_ID', primary_key=True, serialize=False)),
                ('titulo_alternativo', models.CharField(db_column='MAT_TITULO_ALTERNATIVO', max_length=200)),
                ('codigo_lenguaje', models.CharField(db_column='MAT_CODIGO_LENGUAJE', max_length=10)),
                ('vigente', models.BooleanField(db_column='MAT_VIGENTE', default=True)),
                ('manga', models.ForeignKey(db_column='MAT_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.manga')),
            ],
            options={
                'db_table': 'apicore_manga_alt_titulo',
            },
        ),
        migrations.CreateModel(
            name='manga_autor',
            fields=[
                ('id', models.BigAutoField(db_column='MAU_ID', primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('author', 'author'), ('illustrator', 'illustrator'), ('writer', 'writer'), ('editor', 'editor')], db_column='MAU_ROL', default='author', max_length=20)),
                ('vigente', models.BooleanField(db_column='MAU_VIGENTE', default=True)),
                ('autor', models.ForeignKey(db_column='MAU_AUTOR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.autores')),
                ('manga', models.ForeignKey(db_column='MAU_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.manga')),
            ],
            options={
                'db_table': 'apicore_manga_autor',
            },
        ),
        migrations.CreateModel(
            name='manga_cover',
            fields=[
                ('id', models.BigAutoField(db_column='MCV_ID', primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(db_column='MCV_URL_IMAGEN', max_length=255)),
                ('tipo_cover', models.CharField(choices=[('main', 'main'), ('thumbnail', 'thumbnail'), ('banner', 'banner'), ('extra', 'extra')], db_column='MCV_COVER_TIPO', default='main', max_length=20)),
                ('vigente', models.BooleanField(db_column='MCV_VIGENTE', default=True)),
                ('manga', models.ForeignKey(db_column='MCV_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.manga')),
            ],
            options={
                'db_table': 'apicore_manga_cover',
            },
        ),
        migrations.CreateModel(
            name='manga_tag',
            fields=[
                ('id', models.BigAutoField(db_column='MTG_ID', primary_key=True, serialize=False)),
                ('vigente', models.BooleanField(db_column='MTG_VIGENTE', default=True)),
                ('manga', models.ForeignKey(db_column='MTG_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.manga')),
                ('tag', models.ForeignKey(db_column='MTG_TAG_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.tags')),
            ],
            options={
                'db_table': 'apicore_manga_tag',
            },
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(db_column='CHR_ID', primary_key=True, serialize=False)),
                ('capitulo_numero', models.DecimalField(db_column='CHR_CAPITULO_NUMERO', decimal_places=2, max_digits=6)),
                ('titulo', models.CharField(db_column='CHR_TITULO', max_length=200, null=True)),
                ('volumen_numero', models.DecimalField(db_column='CHR_VOLUMEN_NUMERO', decimal_places=2, max_digits=6, null=True)),
                ('pages', models.JSONField(db_column='CHR_PAGES', default=dict, null=True)),
                ('manga', models.ForeignKey(db_column='CHR_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCore.manga')),
            ],
            options={
                'db_table': 'apicore_chapter',
                'indexes': [models.Index(fields=['manga', 'capitulo_numero'], name='chapter_manga_num_idx')],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('allow', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCore.permission')),
            ],
            options={
                'unique_together': {('user', 'group', 'content_type', 'object_id', 'permission')},
            },
        ),
    ]
