# Generated by Django 5.2.6 on 2025-12-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga_cover',
            name='manga',
            field=models.ForeignKey(db_column='MCV_MANGA_ID', on_delete=django.db.models.deletion.PROTECT, related_name='covers', to='ApiCore.manga'),
        ),
    ]
