# Generated by Django 5.2.8 on 2025-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0003_alter_manga_tag_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='slug',
            field=models.SlugField(blank=True, db_column='MNG_SLUG', max_length=255, null=True, unique=True),
        ),
    ]
