# Generated by Django 5.2.6 on 2026-02-13 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCore', '0004_manga_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('home_only', 'Home Only'), ('premium', 'Premium'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='home_only', max_length=20)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
                ('banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'permissions': [('view_nsfw_content', 'Can view NSFW content'), ('view_premium_content', 'Can view premium content'), ('access_admin_panel', 'Can access admin panel'), ('manage_users', 'Can manage users'), ('manage_manga', 'Can manage manga'), ('manage_chapters', 'Can manage chapters'), ('view_analytics', 'Can view analytics'), ('moderate_comments', 'Can moderate comments'), ('moderate_reports', 'Can moderate reports')],
            },
        ),
    ]
